// JS Effects, Cursors, Utils, Audio, Games, Easter Eggs - BEEFED UP EDITION

window.renderJsLibrary = () => {
    // EFFECTS TAB - 16 presets
    const effects = [
        { name: '❄️ Falling Snow', code: `(function(){var style=document.createElement('style');style.innerHTML='@keyframes snowfall{0%{transform:translateY(-10px)}100%{transform:translateY(100vh)}}.snowflake{position:fixed;color:white;animation:snowfall linear infinite;z-index:9999;pointer-events:none}';document.head.appendChild(style);setInterval(()=>{var f=document.createElement('div');f.className='snowflake';f.innerText='❄';f.style.left=Math.random()*100+'vw';f.style.animationDuration=Math.random()*3+2+'s';f.style.fontSize=Math.random()*20+10+'px';document.body.appendChild(f);setTimeout(()=>f.remove(),5000)},200)})();` },
        { name: '🎉 Confetti Rain', code: `(function(){const colors=['#ff0','#f00','#0f0','#00f','#f0f','#0ff'];setInterval(()=>{const c=document.createElement('div');c.style.cssText='position:fixed;left:'+Math.random()*100+'vw;top:-10px;width:10px;height:10px;background:'+colors[Math.floor(Math.random()*colors.length)]+';z-index:9999;transform:rotate('+Math.random()*360+'deg)';document.body.appendChild(c);let top=-10;const i=setInterval(()=>{top+=5;c.style.top=top+'px';if(top>window.innerHeight){clearInterval(i);c.remove()}},20)},100)})();` },
        { name: '📺 Matrix Rain', code: `(function(){var c=document.createElement('canvas');c.style.cssText='position:fixed;top:0;left:0;width:100%;height:100%;z-index:-1;pointer-events:none';document.body.appendChild(c);var ctx=c.getContext('2d');c.width=window.innerWidth;c.height=window.innerHeight;var letters='01'.split(''),fontSize=10,columns=c.width/fontSize,drops=[];for(var x=0;x<columns;x++)drops[x]=1;function draw(){ctx.fillStyle='rgba(0,0,0,0.05)';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#0F0';ctx.font=fontSize+'px monospace';for(var i=0;i<drops.length;i++){var text=letters[Math.floor(Math.random()*letters.length)];ctx.fillText(text,i*fontSize,drops[i]*fontSize);if(drops[i]*fontSize>c.height&&Math.random()>0.975)drops[i]=0;drops[i]++}}setInterval(draw,33)})();` },
        { name: '💿 Bouncing DVD', code: `(function(){var d=document.createElement('div');d.innerText='DVD';d.style.cssText='position:fixed;font-weight:bold;font-size:20px;color:white;z-index:9999;pointer-events:none';document.body.appendChild(d);var x=0,y=0,dx=2,dy=2;setInterval(()=>{x+=dx;y+=dy;if(x+d.offsetWidth>window.innerWidth||x<0)dx=-dx;if(y+d.offsetHeight>window.innerHeight||y<0)dy=-dy;d.style.left=x+'px';d.style.top=y+'px'},10)})();` },
        { name: '🎆 Fireworks', code: `(function(){document.addEventListener('click',e=>{for(let i=0;i<20;i++){const p=document.createElement('div');p.style.cssText='position:fixed;width:8px;height:8px;border-radius:50%;background:hsl('+Math.random()*360+',100%,50%);z-index:9999;pointer-events:none;left:'+e.clientX+'px;top:'+e.clientY+'px';document.body.appendChild(p);const angle=Math.random()*Math.PI*2,speed=Math.random()*5+2;let vx=Math.cos(angle)*speed,vy=Math.sin(angle)*speed,op=1;const int=setInterval(()=>{vx*=0.98;vy+=0.1;op-=0.02;p.style.left=parseFloat(p.style.left)+vx+'px';p.style.top=parseFloat(p.style.top)+vy+'px';p.style.opacity=op;if(op<=0){clearInterval(int);p.remove()}},20)}})})();` },
        { name: '🫧 Bubbles', code: `(function(){setInterval(()=>{const b=document.createElement('div');const size=Math.random()*30+10;b.style.cssText='position:fixed;left:'+Math.random()*100+'vw;bottom:-50px;width:'+size+'px;height:'+size+'px;border-radius:50%;border:2px solid rgba(255,255,255,0.5);background:radial-gradient(circle at 30% 30%,rgba(255,255,255,0.8),transparent);z-index:9998;pointer-events:none';document.body.appendChild(b);let bottom=-50;const int=setInterval(()=>{bottom+=2;b.style.bottom=bottom+'px';if(bottom>window.innerHeight+50){clearInterval(int);b.remove()}},30)},300)})();` },
        { name: '✨ Sparkle Trail', code: `(function(){const colors=['#ff00cc','#00f0ff','#ccff00','#ffffff'];document.addEventListener('mousemove',e=>{if(Math.random()>0.5)return;const p=document.createElement('div');p.style.cssText='position:fixed;left:'+e.clientX+'px;top:'+e.clientY+'px;width:4px;height:4px;background:'+colors[Math.floor(Math.random()*colors.length)]+';border-radius:50%;pointer-events:none;z-index:99999';document.body.appendChild(p);let op=1,top=e.clientY;const int=setInterval(()=>{op-=0.1;top+=2;p.style.opacity=op;p.style.top=top+'px';if(op<=0){clearInterval(int);p.remove()}},50)})})();` },
        { name: '⚡ Lightning', code: `(function(){setInterval(()=>{if(Math.random()>0.95){document.body.style.filter='brightness(3)';setTimeout(()=>document.body.style.filter='none',50);setTimeout(()=>{document.body.style.filter='brightness(2)';setTimeout(()=>document.body.style.filter='none',30)},100)}},100)})();` },
        { name: '🔥 Fire Effect', code: `(function(){const fire=document.createElement('div');fire.style.cssText='position:fixed;bottom:0;left:0;width:100%;height:100px;background:linear-gradient(to top,#ff4500,#ff6600,#ff8c00,transparent);z-index:9998;pointer-events:none;animation:flicker 0.1s infinite';const style=document.createElement('style');style.innerHTML='@keyframes flicker{0%,100%{opacity:0.9}50%{opacity:1}}';document.head.appendChild(style);document.body.appendChild(fire)})();` },
        { name: '💧 Water Ripple', code: `(function(){document.addEventListener('click',e=>{const r=document.createElement('div');r.style.cssText='position:fixed;left:'+(e.clientX-25)+'px;top:'+(e.clientY-25)+'px;width:50px;height:50px;border:2px solid #00bfff;border-radius:50%;z-index:9999;pointer-events:none;animation:ripple 1s ease-out';const style=document.createElement('style');style.innerHTML='@keyframes ripple{to{transform:scale(4);opacity:0}}';document.head.appendChild(style);document.body.appendChild(r);setTimeout(()=>r.remove(),1000)})})();` },
        { name: '🌧️ Rain', code: `(function(){const style=document.createElement('style');style.innerHTML='@keyframes rain{to{transform:translateY(100vh)}}';document.head.appendChild(style);setInterval(()=>{const drop=document.createElement('div');drop.style.cssText='position:fixed;left:'+Math.random()*100+'vw;top:-20px;width:2px;height:20px;background:linear-gradient(transparent,#6af);z-index:9998;pointer-events:none;animation:rain '+(Math.random()*0.5+0.3)+'s linear';document.body.appendChild(drop);setTimeout(()=>drop.remove(),800)},30)})();` },
        { name: '🍂 Falling Leaves', code: `(function(){const leaves=['🍂','🍁','🍃'];setInterval(()=>{const l=document.createElement('div');l.innerText=leaves[Math.floor(Math.random()*leaves.length)];l.style.cssText='position:fixed;left:'+Math.random()*100+'vw;top:-30px;font-size:'+(Math.random()*20+15)+'px;z-index:9998;pointer-events:none;animation:leaffall '+(Math.random()*3+4)+'s linear';const style=document.createElement('style');style.innerHTML='@keyframes leaffall{to{transform:translateY(110vh) rotate(720deg)}}';document.head.appendChild(style);document.body.appendChild(l);setTimeout(()=>l.remove(),7000)},500)})();` },
        { name: '🌸 Petals', code: `(function(){setInterval(()=>{const p=document.createElement('div');p.innerText='🌸';p.style.cssText='position:fixed;left:'+Math.random()*100+'vw;top:-30px;font-size:'+(Math.random()*15+10)+'px;z-index:9998;pointer-events:none;opacity:0.8';document.body.appendChild(p);let top=-30,left=parseFloat(p.style.left);const int=setInterval(()=>{top+=1;left+=Math.sin(top/20)*0.5;p.style.top=top+'px';p.style.left=left+'vw';if(top>window.innerHeight){clearInterval(int);p.remove()}},30)},400)})();` },
        { name: '⭐ Stars Twinkling', code: `(function(){for(let i=0;i<50;i++){const s=document.createElement('div');s.innerText='✦';s.style.cssText='position:fixed;left:'+Math.random()*100+'vw;top:'+Math.random()*100+'vh;color:#fff;font-size:'+(Math.random()*10+5)+'px;z-index:-1;pointer-events:none;animation:twinkle '+(Math.random()*2+1)+'s ease-in-out infinite';document.body.appendChild(s)}const style=document.createElement('style');style.innerHTML='@keyframes twinkle{0%,100%{opacity:1}50%{opacity:0.3}}';document.head.appendChild(style)})();` },
        { name: '🌌 Aurora', code: `(function(){const a=document.createElement('div');a.style.cssText='position:fixed;top:0;left:0;width:100%;height:100%;background:linear-gradient(180deg,transparent 40%,rgba(0,255,128,0.1) 60%,rgba(0,128,255,0.1) 80%,rgba(128,0,255,0.05));z-index:-1;pointer-events:none;animation:aurora 10s ease-in-out infinite';const style=document.createElement('style');style.innerHTML='@keyframes aurora{0%,100%{filter:hue-rotate(0deg)}50%{filter:hue-rotate(60deg)}}';document.head.appendChild(style);document.body.appendChild(a)})();` },
        { name: '🪩 Disco Ball', code: `(function(){setInterval(()=>{const spot=document.createElement('div');const size=Math.random()*100+50;spot.style.cssText='position:fixed;left:'+Math.random()*100+'vw;top:'+Math.random()*100+'vh;width:'+size+'px;height:'+size+'px;border-radius:50%;background:radial-gradient(circle,hsla('+Math.random()*360+',100%,70%,0.3),transparent);z-index:-1;pointer-events:none';document.body.appendChild(spot);setTimeout(()=>spot.remove(),500)},100)})();` }
    ];
    
    // CURSORS TAB - 10 presets
    const cursors = [
        { name: '✨ Sparkle Trail', code: `(function(){const colors=['#ff00cc','#00f0ff','#ccff00','#fff'];document.addEventListener('mousemove',e=>{if(Math.random()>0.5)return;const p=document.createElement('div');p.style.cssText='position:fixed;left:'+e.clientX+'px;top:'+e.clientY+'px;width:4px;height:4px;background:'+colors[Math.floor(Math.random()*colors.length)]+';border-radius:50%;pointer-events:none;z-index:99999';document.body.appendChild(p);let op=1,top=e.clientY;const int=setInterval(()=>{op-=0.1;top+=2;p.style.opacity=op;p.style.top=top+'px';if(op<=0){clearInterval(int);p.remove()}},50)})})();` },
        { name: '👻 Ghost Trail', code: `(function(){document.addEventListener('mousemove',e=>{const p=document.createElement('div');p.innerText='👻';p.style.cssText='position:fixed;left:'+e.clientX+'px;top:'+e.clientY+'px;pointer-events:none;z-index:99999;font-size:20px';document.body.appendChild(p);setTimeout(()=>p.remove(),500)})})();` },
        { name: '🌈 Rainbow Trail', code: `(function(){let hue=0;document.addEventListener('mousemove',e=>{const p=document.createElement('div');p.style.cssText='position:fixed;left:'+e.clientX+'px;top:'+e.clientY+'px;width:10px;height:10px;background:hsl('+hue+',100%,50%);border-radius:50%;pointer-events:none;z-index:99999';hue=(hue+5)%360;document.body.appendChild(p);setTimeout(()=>p.remove(),300)})})();` },
        { name: '💡 Cursor Glow', code: `(function(){const glow=document.createElement('div');glow.style.cssText='position:fixed;width:100px;height:100px;border-radius:50%;background:radial-gradient(circle,rgba(255,255,255,0.3),transparent);pointer-events:none;z-index:99998;transform:translate(-50%,-50%)';document.body.appendChild(glow);document.addEventListener('mousemove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'})})();` },
        { name: '😀 Emoji Cursor', code: `document.body.style.cursor="url('data:image/svg+xml;utf8,%3Csvg xmlns=%22https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/SVG_Logo.svg/250px-SVG_Logo.svg.png width=%2232%22 height=%2232%22%3E%3Ctext y=%2224%22 style=%22font-size:24px%22%3E👽%3C/text%3E%3C/svg%3E'),auto";` },
        { name: '📝 Text Cursor', code: `document.body.style.cursor="url('data:image/svg+xml;utf8,%3Csvg xmlns=%22https://assets.streamlinehq.com/image/private/w_512,h_512,ar_1/f_auto/v1/icons/1/alien-ywrej8e77js3el64aw4.png/alien-8j0u8oi9mw74qa9mhe3dqo.png?_a=DATAg1AAZAA0 width=%2264%22 height=%2220%22%3E%3Ctext y=%2216%22 style=%22font-size:14px;fill:white%22%3ECLICK ME%3C/text%3E%3C/svg%3E'),auto";` },
        { name: '🔄 Inverted Cursor', code: `document.body.style.cursor='none';const c=document.createElement('div');c.style.cssText='position:fixed;width:20px;height:20px;border-radius:50%;background:#fff;mix-blend-mode:difference;pointer-events:none;z-index:99999';document.body.appendChild(c);document.addEventListener('mousemove',e=>{c.style.left=e.clientX-10+'px';c.style.top=e.clientY-10+'px'});` },
        { name: '🔍 Giant Cursor', code: `document.body.style.cursor='none';const c=document.createElement('div');c.innerHTML='<svg width="60" height="60"><polygon points="0,0 0,40 10,30 20,50 25,48 15,28 30,28" fill="white" stroke="black" stroke-width="2"/></svg>';c.style.cssText='position:fixed;pointer-events:none;z-index:99999';document.body.appendChild(c);document.addEventListener('mousemove',e=>{c.style.left=e.clientX+'px';c.style.top=e.clientY+'px'});` },
        { name: '🔬 Tiny Cursor', code: `document.body.style.cursor='none';const c=document.createElement('div');c.style.cssText='position:fixed;width:4px;height:4px;background:#fff;border-radius:50%;pointer-events:none;z-index:99999';document.body.appendChild(c);document.addEventListener('mousemove',e=>{c.style.left=e.clientX-2+'px';c.style.top=e.clientY-2+'px'});` },
        { name: '✝️ Crosshair', code: `document.body.style.cursor='crosshair';` }
    ];
    
    // UTILS TAB - 14 presets
    const utils = [
        { name: '🕰️ Digital Clock', code: `(function(){const d=document.createElement('div');d.style.cssText='position:fixed;bottom:10px;right:10px;background:#000;color:#0f0;font-family:monospace;padding:5px 10px;border:1px solid #0f0;z-index:9999';document.body.appendChild(d);setInterval(()=>d.innerText=new Date().toLocaleTimeString(),1000)})();` },
        { name: '🔝 Scroll to Top', code: `(function(){const btn=document.createElement('button');btn.innerHTML='⬆️';btn.style.cssText='position:fixed;bottom:20px;right:20px;width:50px;height:50px;border-radius:50%;border:none;background:#333;color:#fff;font-size:20px;cursor:pointer;z-index:9999;opacity:0;transition:opacity 0.3s';btn.onclick=()=>window.scrollTo({top:0,behavior:'smooth'});document.body.appendChild(btn);window.addEventListener('scroll',()=>btn.style.opacity=window.scrollY>300?'1':'0')})();` },
        { name: '📊 Reading Progress', code: `(function(){const bar=document.createElement('div');bar.style.cssText='position:fixed;top:0;left:0;height:4px;background:linear-gradient(90deg,#ff0080,#ff8c00);z-index:99999;transition:width 0.1s';document.body.appendChild(bar);window.addEventListener('scroll',()=>{const pct=window.scrollY/(document.body.scrollHeight-window.innerHeight)*100;bar.style.width=pct+'%'})})();` },
        { name: '🌙 Dark Mode Toggle', code: `(function(){const btn=document.createElement('button');btn.innerHTML='🌙';btn.style.cssText='position:fixed;top:10px;right:10px;padding:10px;border:none;background:#333;border-radius:50%;cursor:pointer;z-index:9999;font-size:20px';let dark=false;btn.onclick=()=>{dark=!dark;document.body.style.filter=dark?'invert(1) hue-rotate(180deg)':'none';btn.innerHTML=dark?'☀️':'🌙'};document.body.appendChild(btn)})();` },
        { name: '🔠 Font Size Controls', code: `(function(){const c=document.createElement('div');c.innerHTML='<button id="fs-">A-</button><button id="fs+">A+</button>';c.style.cssText='position:fixed;top:10px;left:10px;z-index:9999';c.querySelectorAll('button').forEach(b=>b.style.cssText='padding:5px 10px;margin:2px;cursor:pointer');document.body.appendChild(c);let size=100;document.getElementById('fs-').onclick=()=>document.body.style.fontSize=(size-=10)+'%';document.getElementById('fs+').onclick=()=>document.body.style.fontSize=(size+=10)+'%'})();` },
        { name: '🖼️ Fullscreen Toggle', code: `(function(){const btn=document.createElement('button');btn.innerHTML='⛶';btn.style.cssText='position:fixed;bottom:10px;left:10px;padding:10px;border:none;background:#333;color:#fff;border-radius:5px;cursor:pointer;z-index:9999;font-size:20px';btn.onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();document.body.appendChild(btn)})();` },
        { name: '📋 Copy to Clipboard', code: `(function(){document.addEventListener('dblclick',e=>{const sel=window.getSelection().toString();if(sel){navigator.clipboard.writeText(sel);const t=document.createElement('div');t.innerText='Copied!';t.style.cssText='position:fixed;top:20px;left:50%;transform:translateX(-50%);background:#333;color:#fff;padding:10px 20px;border-radius:5px;z-index:99999';document.body.appendChild(t);setTimeout(()=>t.remove(),1500)}})})();` },
        { name: '🔗 Share Buttons', code: `(function(){const c=document.createElement('div');c.innerHTML='<a href="https://twitter.com/share?url='+encodeURIComponent(location.href)+'" target="_blank">🐦</a> <a href="https://www.facebook.com/sharer.php?u='+encodeURIComponent(location.href)+'" target="_blank">📘</a>';c.style.cssText='position:fixed;bottom:10px;left:50%;transform:translateX(-50%);z-index:9999;font-size:24px';c.querySelectorAll('a').forEach(a=>a.style.margin='0 5px');document.body.appendChild(c)})();` },
        { name: '🖨️ Print Button', code: `(function(){const btn=document.createElement('button');btn.innerHTML='🖨️ Print';btn.style.cssText='position:fixed;top:10px;right:70px;padding:8px 15px;border:none;background:#333;color:#fff;border-radius:5px;cursor:pointer;z-index:9999';btn.onclick=()=>window.print();document.body.appendChild(btn)})();` },
        { name: '⬅️ Back Button', code: `(function(){const btn=document.createElement('button');btn.innerHTML='← Back';btn.style.cssText='position:fixed;top:10px;left:10px;padding:8px 15px;border:none;background:#333;color:#fff;border-radius:5px;cursor:pointer;z-index:9999';btn.onclick=()=>history.back();document.body.appendChild(btn)})();` },
        { name: '🌈 Title Marquee', code: `(function(){var msg=' Welcome to my site! ';var pos=0;setInterval(()=>{document.title=msg.substring(pos)+msg.substring(0,pos);pos++;if(pos>msg.length)pos=0},200)})();` },
        { name: '⌨️ Keyboard Shortcuts', code: `(function(){document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key==='/')alert('Keyboard Shortcuts:\\n• Ctrl+/ - This help\\n• Ctrl+Home - Top\\n• Ctrl+End - Bottom');if(e.ctrlKey&&e.key==='Home')window.scrollTo(0,0);if(e.ctrlKey&&e.key==='End')window.scrollTo(0,document.body.scrollHeight)})})();` },
        { name: '🔗 Anchor Links', code: `(function(){document.querySelectorAll('h1,h2,h3').forEach((h,i)=>{h.id='heading-'+i;const a=document.createElement('a');a.href='#heading-'+i;a.innerText=' 🔗';a.style.opacity='0.5';h.appendChild(a)})})();` },
        { name: '🚫 No Right Click', code: `document.addEventListener('contextmenu',e=>e.preventDefault());` }
    ];

    // AUDIO TAB - 6 presets
    const audio = [
        { name: '🎵 BG Music Player', code: `(function(){const a=document.createElement('audio');a.src='https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3';a.loop=true;const btn=document.createElement('button');btn.innerHTML='🎵 Play Music';btn.style.cssText='position:fixed;bottom:60px;right:10px;padding:10px;border:none;background:#333;color:#fff;border-radius:5px;cursor:pointer;z-index:9999';let playing=false;btn.onclick=()=>{playing?a.pause():a.play();playing=!playing;btn.innerHTML=playing?'⏸️ Pause':'🎵 Play Music'};document.body.appendChild(btn)})();` },
        { name: '🔊 Hover Sound', code: `(function(){const ctx=new(window.AudioContext||window.webkitAudioContext)();document.querySelectorAll('a,button').forEach(el=>{el.addEventListener('mouseenter',()=>{const o=ctx.createOscillator();o.type='sine';o.frequency.value=800;o.connect(ctx.destination);o.start();o.stop(ctx.currentTime+0.05)})})})();` },
        { name: '🖱️ Click Sound', code: `(function(){const ctx=new(window.AudioContext||window.webkitAudioContext)();document.addEventListener('click',()=>{const o=ctx.createOscillator();o.type='square';o.frequency.value=600;o.connect(ctx.destination);o.start();o.stop(ctx.currentTime+0.03)})})();` },
        { name: '🌊 Ambient Ocean', code: `(function(){const ctx=new(window.AudioContext||window.webkitAudioContext)();const noise=ctx.createBufferSource();const buffer=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate);const data=buffer.getChannelData(0);for(let i=0;i<buffer.length;i++)data[i]=Math.random()*2-1;noise.buffer=buffer;noise.loop=true;const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=500;noise.connect(filter);filter.connect(ctx.destination);noise.start();const btn=document.createElement('button');btn.innerHTML='🌊 Stop Ocean';btn.style.cssText='position:fixed;bottom:100px;right:10px;padding:8px;border:none;background:#333;color:#fff;border-radius:5px;cursor:pointer;z-index:9999';btn.onclick=()=>noise.stop();document.body.appendChild(btn)})();` },
        { name: '🎮 8-bit Sounds', code: `(function(){const ctx=new(window.AudioContext||window.webkitAudioContext)();window.play8bit=(freq,dur)=>{const o=ctx.createOscillator();o.type='square';o.frequency.value=freq;const g=ctx.createGain();g.gain.setValueAtTime(0.3,ctx.currentTime);g.gain.exponentialRampToValueAtTime(0.01,ctx.currentTime+dur);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+dur)};document.addEventListener('click',()=>play8bit(440,0.1));console.log('8-bit sounds enabled! Use play8bit(freq, duration)')})();` },
        { name: '🔔 UI Sounds Pack', code: `(function(){const ctx=new(window.AudioContext||window.webkitAudioContext)();const sounds={click:[600,0.05],hover:[800,0.03],success:[880,0.1],error:[220,0.2]};window.playUI=type=>{const[f,d]=sounds[type]||[440,0.1];const o=ctx.createOscillator();o.frequency.value=f;o.connect(ctx.destination);o.start();o.stop(ctx.currentTime+d)};document.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>playUI('click')));console.log('UI sounds loaded! Use playUI("click"|"hover"|"success"|"error")')})();` }
    ];

    // GAMES TAB - 9 presets
    const games = [
        { name: '🏓 Pong', code: `(function(){const c=document.createElement('canvas');c.width=400;c.height=300;c.style.cssText='position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);background:#000;z-index:99999;border:2px solid #fff';document.body.appendChild(c);const ctx=c.getContext('2d');let py=130,by=150,bx=200,bdx=3,bdy=2;document.addEventListener('mousemove',e=>py=Math.min(250,Math.max(0,e.clientY-c.getBoundingClientRect().top-25)));setInterval(()=>{ctx.fillStyle='#000';ctx.fillRect(0,0,400,300);ctx.fillStyle='#fff';ctx.fillRect(10,py,10,50);ctx.fillRect(380,by,10,50);ctx.beginPath();ctx.arc(bx,by,8,0,Math.PI*2);ctx.fill();bx+=bdx;by+=bdy;if(by<0||by>300)bdy=-bdy;if(bx<20&&by>py&&by<py+50)bdx=-bdx;if(bx>380){by=150;bx=200}if(bx>370)by+=(by<by+25?2:-2);if(bx<0){bx=200;by=150}},16);const close=document.createElement('button');close.innerHTML='✕';close.style.cssText='position:fixed;top:calc(50% - 160px);left:calc(50% + 180px);z-index:99999;background:#f00;color:#fff;border:none;cursor:pointer;padding:5px 10px';close.onclick=()=>{c.remove();close.remove()};document.body.appendChild(close)})();` },
        { name: '🐍 Snake', code: `(function(){const c=document.createElement('canvas');c.width=300;c.height=300;c.style.cssText='position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);background:#000;z-index:99999;border:2px solid #0f0';document.body.appendChild(c);const ctx=c.getContext('2d');let snake=[{x:150,y:150}],dir={x:15,y:0},food={x:75,y:75};document.addEventListener('keydown',e=>{if(e.key==='ArrowUp'&&dir.y===0)dir={x:0,y:-15};if(e.key==='ArrowDown'&&dir.y===0)dir={x:0,y:15};if(e.key==='ArrowLeft'&&dir.x===0)dir={x:-15,y:0};if(e.key==='ArrowRight'&&dir.x===0)dir={x:15,y:0}});setInterval(()=>{const head={x:snake[0].x+dir.x,y:snake[0].y+dir.y};if(head.x<0||head.x>=300||head.y<0||head.y>=300){snake=[{x:150,y:150}];return}snake.unshift(head);if(head.x===food.x&&head.y===food.y){food={x:Math.floor(Math.random()*20)*15,y:Math.floor(Math.random()*20)*15}}else{snake.pop()}ctx.fillStyle='#000';ctx.fillRect(0,0,300,300);ctx.fillStyle='#0f0';snake.forEach(s=>ctx.fillRect(s.x,s.y,14,14));ctx.fillStyle='#f00';ctx.fillRect(food.x,food.y,14,14)},150);const close=document.createElement('button');close.innerHTML='✕';close.style.cssText='position:fixed;top:calc(50% - 165px);left:calc(50% + 135px);z-index:99999;background:#f00;color:#fff;border:none;cursor:pointer;padding:5px 10px';close.onclick=()=>{c.remove();close.remove()};document.body.appendChild(close)})();` },
        { name: '🧱 Breakout', code: `(function(){const c=document.createElement('canvas');c.width=400;c.height=300;c.style.cssText='position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);background:#000;z-index:99999;border:2px solid #fff';document.body.appendChild(c);const ctx=c.getContext('2d');let px=175,bx=200,by=250,bdx=3,bdy=-3;const bricks=[];for(let i=0;i<8;i++)for(let j=0;j<4;j++)bricks.push({x:i*48+10,y:j*20+10,alive:true});document.addEventListener('mousemove',e=>px=Math.min(350,Math.max(0,e.clientX-c.getBoundingClientRect().left-25)));setInterval(()=>{ctx.fillStyle='#000';ctx.fillRect(0,0,400,300);ctx.fillStyle='#fff';ctx.fillRect(px,280,50,10);ctx.beginPath();ctx.arc(bx,by,6,0,Math.PI*2);ctx.fill();bricks.forEach(b=>{if(b.alive){ctx.fillStyle='#0ff';ctx.fillRect(b.x,b.y,45,18);if(bx>b.x&&bx<b.x+45&&by>b.y&&by<b.y+18){b.alive=false;bdy=-bdy}}});bx+=bdx;by+=bdy;if(bx<6||bx>394)bdx=-bdx;if(by<6)bdy=-bdy;if(by>274&&bx>px&&bx<px+50)bdy=-bdy;if(by>300){bx=200;by=250;bdy=-3}},16);const close=document.createElement('button');close.innerHTML='✕';close.style.cssText='position:fixed;top:calc(50% - 165px);left:calc(50% + 185px);z-index:99999;background:#f00;color:#fff;border:none;cursor:pointer;padding:5px 10px';close.onclick=()=>{c.remove();close.remove()};document.body.appendChild(close)})();` },
        { name: '🐦 Flappy Clone', code: `(function(){const c=document.createElement('canvas');c.width=300;c.height=400;c.style.cssText='position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);background:#87ceeb;z-index:99999;border:2px solid #333';document.body.appendChild(c);const ctx=c.getContext('2d');let by=200,bv=0,pipes=[],score=0;document.addEventListener('click',()=>bv=-8);setInterval(()=>{bv+=0.5;by+=bv;ctx.fillStyle='#87ceeb';ctx.fillRect(0,0,300,400);ctx.fillStyle='#ff0';ctx.beginPath();ctx.arc(50,by,15,0,Math.PI*2);ctx.fill();if(Math.random()<0.02)pipes.push({x:300,gap:Math.random()*200+100});pipes.forEach(p=>{p.x-=3;ctx.fillStyle='#0a0';ctx.fillRect(p.x,0,40,p.gap);ctx.fillRect(p.x,p.gap+100,40,300);if(50>p.x&&50<p.x+40&&(by<p.gap||by>p.gap+100)){by=200;bv=0;pipes=[];score=0}if(p.x==47)score++});pipes=pipes.filter(p=>p.x>-40);ctx.fillStyle='#000';ctx.font='20px Arial';ctx.fillText('Score: '+score,10,30);if(by>400||by<0){by=200;bv=0;pipes=[];score=0}},30);const close=document.createElement('button');close.innerHTML='✕';close.style.cssText='position:fixed;top:calc(50% - 215px);left:calc(50% + 135px);z-index:99999;background:#f00;color:#fff;border:none;cursor:pointer;padding:5px 10px';close.onclick=()=>{c.remove();close.remove()};document.body.appendChild(close)})();` },
        { name: '🍪 Cookie Clicker', code: `(function(){const d=document.createElement('div');d.innerHTML='<div style="font-size:80px;cursor:pointer" id="cookie">🍪</div><div id="count">Cookies: 0</div><button id="auto">Buy Auto (+1/s) - 10🍪</button>';d.style.cssText='position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);background:#8b4513;padding:30px;border-radius:20px;text-align:center;z-index:99999;color:#fff';document.body.appendChild(d);let cookies=0,auto=0;d.querySelector('#cookie').onclick=()=>{cookies++;d.querySelector('#count').innerText='Cookies: '+cookies};d.querySelector('#auto').onclick=()=>{if(cookies>=10){cookies-=10;auto++;d.querySelector('#count').innerText='Cookies: '+cookies}};setInterval(()=>{cookies+=auto;d.querySelector('#count').innerText='Cookies: '+cookies},1000);const close=document.createElement('button');close.innerHTML='✕';close.style.cssText='position:absolute;top:5px;right:5px;background:#f00;color:#fff;border:none;cursor:pointer;padding:5px 10px';close.onclick=()=>d.remove();d.appendChild(close)})();` },
        { name: '🎰 Slot Machine', code: `(function(){const emojis=['🍒','🍋','🍊','🍇','⭐','7️⃣'];const d=document.createElement('div');d.innerHTML='<div style="font-size:40px;display:flex;gap:10px;justify-content:center" id="slots"><span>❓</span><span>❓</span><span>❓</span></div><button id="spin" style="margin-top:15px;padding:10px 30px;font-size:18px;cursor:pointer">🎰 SPIN</button><div id="result"></div>';d.style.cssText='position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);background:linear-gradient(#4a0,#280);padding:30px;border-radius:15px;text-align:center;z-index:99999;border:5px solid gold';document.body.appendChild(d);d.querySelector('#spin').onclick=()=>{const r=Array(3).fill().map(()=>emojis[Math.floor(Math.random()*emojis.length)]);d.querySelector('#slots').innerHTML=r.map(e=>'<span>'+e+'</span>').join('');d.querySelector('#result').innerHTML=r[0]===r[1]&&r[1]===r[2]?'<span style="color:gold;font-size:24px">🎉 JACKPOT!</span>':''};const close=document.createElement('button');close.innerHTML='✕';close.style.cssText='position:absolute;top:5px;right:5px;background:#f00;color:#fff;border:none;cursor:pointer;padding:5px 10px';close.onclick=()=>d.remove();d.appendChild(close)})();` },
        { name: '🎡 Wheel of Fortune', code: `(function(){const prizes=['$100','$50','$200','LOSE','$500','$25'];const c=document.createElement('canvas');c.width=300;c.height=350;c.style.cssText='position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);z-index:99999';document.body.appendChild(c);const ctx=c.getContext('2d');let angle=0,spinning=false;function draw(){ctx.clearRect(0,0,300,350);prizes.forEach((p,i)=>{ctx.beginPath();ctx.moveTo(150,150);ctx.arc(150,150,140,i*Math.PI/3+angle,(i+1)*Math.PI/3+angle);ctx.fillStyle='hsl('+(i*60)+',70%,50%)';ctx.fill();ctx.stroke();ctx.save();ctx.translate(150,150);ctx.rotate(i*Math.PI/3+Math.PI/6+angle);ctx.fillStyle='#fff';ctx.font='14px Arial';ctx.fillText(p,50,5);ctx.restore()});ctx.beginPath();ctx.moveTo(150,5);ctx.lineTo(140,25);ctx.lineTo(160,25);ctx.fillStyle='#f00';ctx.fill()}draw();c.onclick=()=>{if(spinning)return;spinning=true;let speed=0.3;const int=setInterval(()=>{angle+=speed;speed*=0.98;draw();if(speed<0.001){clearInterval(int);spinning=false;const idx=Math.floor(((2*Math.PI-angle%(2*Math.PI))/(Math.PI/3)))%6;alert('You won: '+prizes[idx])}},16)};const close=document.createElement('button');close.innerHTML='✕ Close';close.style.cssText='position:fixed;top:calc(50% + 180px);left:50%;transform:translateX(-50%);z-index:99999;background:#f00;color:#fff;border:none;cursor:pointer;padding:8px 15px';close.onclick=()=>{c.remove();close.remove()};document.body.appendChild(close)})();` },
        { name: '❓ Quiz Engine', code: `(function(){const qs=[{q:'What is 2+2?',a:['3','4','5'],c:1},{q:'Capital of France?',a:['London','Paris','Berlin'],c:1},{q:'Largest planet?',a:['Earth','Jupiter','Mars'],c:1}];let i=0,score=0;const d=document.createElement('div');d.style.cssText='position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);background:#333;padding:30px;border-radius:15px;z-index:99999;color:#fff;min-width:300px';function show(){d.innerHTML='<h3>'+qs[i].q+'</h3>'+qs[i].a.map((a,j)=>'<button style="display:block;width:100%;margin:5px 0;padding:10px;cursor:pointer" onclick="window.quizAnswer('+j+')">'+a+'</button>').join('')+'<div>Score: '+score+'/'+qs.length+'</div>'}window.quizAnswer=j=>{if(j===qs[i].c)score++;i++;if(i<qs.length)show();else{d.innerHTML='<h3>Quiz Complete!</h3><p>Score: '+score+'/'+qs.length+'</p><button onclick="this.parentElement.remove()">Close</button>'}};show();document.body.appendChild(d)})();` },
        { name: '⏱️ Idle Game', code: `(function(){const d=document.createElement('div');d.innerHTML='<h3>💰 Idle Clicker</h3><div id="money">$0</div><button id="click">Click for $1</button><br><button id="buy">Buy Worker ($10) - 0 owned</button>';d.style.cssText='position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);background:#2a2a4a;padding:25px;border-radius:15px;z-index:99999;color:#fff;text-align:center';d.querySelectorAll('button').forEach(b=>b.style.cssText='margin:5px;padding:10px 20px;cursor:pointer');document.body.appendChild(d);let money=0,workers=0;d.querySelector('#click').onclick=()=>{money++;update()};d.querySelector('#buy').onclick=()=>{if(money>=10){money-=10;workers++;update()}};function update(){d.querySelector('#money').innerText='$'+money;d.querySelector('#buy').innerText='Buy Worker ($10) - '+workers+' owned'}setInterval(()=>{money+=workers;update()},1000);const close=document.createElement('button');close.innerHTML='✕';close.style.cssText='position:absolute;top:5px;right:5px;background:#f00;color:#fff;border:none;cursor:pointer;padding:3px 8px';close.onclick=()=>d.remove();d.appendChild(close)})();` }
    ];

    // EASTER EGGS TAB - 7 presets  
    const eggs = [
        { name: '🎮 Konami Code', code: `(function(){const code=['ArrowUp','ArrowUp','ArrowDown','ArrowDown','ArrowLeft','ArrowRight','ArrowLeft','ArrowRight','b','a'];let cur=0;document.addEventListener('keydown',e=>{if(e.key===code[cur]){cur++;if(cur===code.length){alert('🎉 KONAMI CODE ACTIVATED! You found the secret!');document.body.style.animation='rainbow 2s infinite';const style=document.createElement('style');style.innerHTML='@keyframes rainbow{0%{filter:hue-rotate(0deg)}100%{filter:hue-rotate(360deg)}}';document.head.appendChild(style);cur=0}}else cur=0})})();` },
        { name: '🖱️ Secret Click Combo', code: `(function(){let clicks=0,timer;document.addEventListener('click',()=>{clicks++;clearTimeout(timer);timer=setTimeout(()=>clicks=0,1000);if(clicks===5){alert('🔓 Secret unlocked! You clicked 5 times fast!');document.body.innerHTML+='<div style="position:fixed;top:50%;left:50%;transform:translate(-50%,-50%);font-size:100px;z-index:99999">🎊</div>'}})})();` },
        { name: '📜 Hidden Message', code: `(function(){console.log('%c🕵️ SECRET MESSAGE','font-size:30px;color:red');console.log('%cYou found the hidden console message! Share this secret code: COAIEXIST2025','font-size:16px;color:cyan');const d=document.createElement('div');d.innerText='Check the console for a secret message! (F12)';d.style.cssText='position:fixed;bottom:50px;left:50%;transform:translateX(-50%);background:#000;color:#0f0;padding:10px;z-index:9999;font-family:monospace';document.body.appendChild(d);setTimeout(()=>d.remove(),5000)})();` },
        { name: '🎵 Rickroll Trigger', code: `(function(){let typed='';document.addEventListener('keypress',e=>{typed+=e.key.toLowerCase();if(typed.includes('rick')){window.open('https://www.youtube.com/watch?v=dQw4w9WgXcQ','_blank');typed=''}if(typed.length>10)typed=typed.slice(-10)})})();` },
        { name: '📎 Clippy Returns', code: `(function(){const clippy=document.createElement('div');clippy.innerHTML='📎<div style="background:#ffffc0;border:1px solid #000;padding:10px;border-radius:5px;margin-top:5px;font-size:12px">It looks like you\\'re browsing a website!<br>Would you like help?<br><button onclick="this.parentElement.parentElement.remove()">No thanks</button></div>';clippy.style.cssText='position:fixed;bottom:20px;right:20px;font-size:50px;z-index:99999;cursor:pointer';document.body.appendChild(clippy)})();` },
        { name: '👶 Dancing Baby', code: `(function(){const baby=document.createElement('div');baby.innerText='👶';baby.style.cssText='position:fixed;bottom:20px;left:50%;font-size:80px;z-index:99999;animation:dance 0.5s infinite';const style=document.createElement('style');style.innerHTML='@keyframes dance{0%,100%{transform:translateX(-50%) rotate(-10deg)}50%{transform:translateX(-50%) rotate(10deg)}}';document.head.appendChild(style);document.body.appendChild(baby);setTimeout(()=>baby.remove(),10000)})();` },
        { name: '🌈 Nyan Cat', code: `(function(){const nyan=document.createElement('div');nyan.innerHTML='<span style="animation:nyanMove 3s linear infinite;display:inline-block">🌈🐱</span>';nyan.style.cssText='position:fixed;top:50%;left:-100px;font-size:40px;z-index:99999;white-space:nowrap';const style=document.createElement('style');style.innerHTML='@keyframes nyanMove{0%{transform:translateX(0)}100%{transform:translateX(calc(100vw + 200px))}}';document.head.appendChild(style);document.body.appendChild(nyan);setTimeout(()=>nyan.remove(),3000)})();` }
    ];

    const renderGrid = (items, id) => {
        const el = document.getElementById(id);
        if (!el) return;
        el.innerHTML = items.map(item => {
            const escapedCode = item.code.replaceAll('`', '\\`').replaceAll('"', '&quot;');
            return `
                <div class="style-card" onclick="window.applyJsPreset(\`${escapedCode}\`)">
                <div style="font-size:20px; margin-bottom:5px;">⚡</div>
                <div>${item.name}</div>
                </div>
            `;
        }).join('');
    };

    renderGrid(effects, 'js-tab-effects');
    renderGrid(cursors, 'js-tab-cursors');
    renderGrid(utils, 'js-tab-utils');
    renderGrid(audio, 'js-tab-audio');
    renderGrid(games, 'js-tab-games');
    renderGrid(eggs, 'js-tab-eggs');
};
